import Handlebars from "handlebars";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { BrainReader } from "@after/core";
import type { Citation } from "@after/core";

/**
 * Generator options
 */
export interface GeneratorOptions {
  projectPath: string;
  includeTimestamp?: boolean;
  includeCitations?: boolean;
}

/**
 * Generated output with metadata
 */
export interface GeneratedOutput {
  content: string;
  citations: Citation[];
  metadata: {
    generatedAt: string;
    generator: string;
    version: string;
  };
}

/**
 * Base Generator
 * 
 * Provides common functionality for all output generators.
 */
export abstract class BaseGenerator {
  protected brainReader: BrainReader;
  protected projectPath: string;
  protected includeTimestamp: boolean;
  protected includeCitations: boolean;

  constructor(brainReader: BrainReader, options: GeneratorOptions) {
    this.brainReader = brainReader;
    this.projectPath = options.projectPath;
    this.includeTimestamp = options.includeTimestamp ?? true;
    this.includeCitations = options.includeCitations ?? true;
  }

  /**
   * Generate output
   */
  abstract generate(): Promise<GeneratedOutput>;

  /**
   * Get the generator name
   */
  abstract getGeneratorName(): string;

  /**
   * Load and compile a Handlebars template
   */
  protected async loadTemplate(templateName: string): Promise<HandlebarsTemplateDelegate> {
    const templatePath = join(__dirname, "../templates", `${templateName}.hbs`);
    const templateContent = await readFile(templatePath, "utf-8");
    return Handlebars.compile(templateContent);
  }

  /**
   * Create output metadata
   */
  protected createMetadata(): GeneratedOutput["metadata"] {
    return {
      generatedAt: new Date().toISOString(),
      generator: this.getGeneratorName(),
      version: "1.0.0",
    };
  }

  /**
   * Format citations as markdown
   */
  protected formatCitations(citations: Citation[]): string {
    if (!this.includeCitations || citations.length === 0) {
      return "";
    }

    const lines = ["\n\n---\n", "\n## Sources\n"];

    for (const citation of citations) {
      lines.push(`- **${citation.file}**${citation.line ? `:${citation.line}` : ""}`);
      if (citation.preview) {
        lines.push(`  > ${citation.preview.slice(0, 100)}...`);
      }
    }

    return lines.join("\n");
  }

  /**
   * Add timestamp footer
   */
  protected addFooter(content: string): string {
    if (!this.includeTimestamp) {
      return content;
    }

    const timestamp = new Date().toLocaleString();
    return `${content}\n\n---\n\n*Generated by After on ${timestamp}*\n`;
  }
}

// Made with Bob
